keys:
  - &age_public_key age12wncach0d3tapa5km0w8hd6pgpsyw8vjqrm6uv55r5lzjlwcvuwqt9dnzk

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *age_public_key
  - path_regex: secrets/[^/]+\.json$
    key_groups:
    - age:
      - *age_public_key