keys:
  - &harkunwar_age age1vtee003rf9tps855tekvj3wq7v5nempgj8wdzwf8uqxwnnp0xe7qtgsjlg # Replace with your actual public key from step 5

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *harkunwar_age
  - path_regex: secrets/[^/]+\.json$
    key_groups:
    - age:
      - *harkunwar_age