# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices = {
    # Root drives (Samsung SSDs 480GB)
    "luks-rpool-ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21136-part2".device = "/dev/disk/by-id/ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21136-part2";
    "luks-rpool-ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21130-part2".device = "/dev/disk/by-id/ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21130-part2";

    # Espresso drives (Samsung SSDs  960GB)
    "luks-espresso-ata-SAMSUNG_MZ7KM960HAHP-00005_S2HTNX0H626552" = {
      device = "/dev/disk/by-id/ata-SAMSUNG_MZ7KM960HAHP-00005_S2HTNX0H626552";
      allowDiscards = true;
    };
    "luks-espresso-ata-SAMSUNG_MZ7KM960HAHP-00005_S2HTNX0HB01819" = {
      device = "/dev/disk/by-id/ata-SAMSUNG_MZ7KM960HAHP-00005_S2HTNX0HB01819";
      allowDiscards = true;
    };

    # Molasses drives (Seagate HDDs)
    "luks-molasses-ata-ST16000NT001-3LV101_ZR6143T5" = {
      device = "/dev/disk/by-id/ata-ST16000NT001-3LV101_ZR6143T5";
    };
    "luks-molasses-ata-ST16000NT001-3LV101_ZR70WRGB" = {
      device = "/dev/disk/by-id/ata-ST16000NT001-3LV101_ZR70WRGB";
    };

  };

  fileSystems."/" =
    {
      device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/DB92-A87A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/espresso" =
    {
      device = "espresso";
      fsType = "zfs";
    };

  fileSystems."/mnt/molasses" =
    {
      device = "molasses";
      fsType = "zfs";
    };

  fileSystems."/mnt/molasses/time-machine" =
    {
      device = "molasses/time-machine";
      fsType = "zfs";
      depends = [ "/mnt/molasses" ];
    };

  fileSystems."/mnt/molasses/private-media" =
    {
      device = "molasses/private-media";
      fsType = "zfs";
      depends = [ "/mnt/molasses" ];
    };

  swapDevices = [
    { device = "/dev/disk/by-id/ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21136-part3"; }
    { device = "/dev/disk/by-id/ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21130-part3"; }
  ];
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.hostId = "dead1212";
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
