# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices = {
    # Root drives (Samsung SSDs 480GB)
    "luks-rpool-ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21136-part2".device = "/dev/disk/by-id/ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21136-part2";
    "luks-rpool-ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21130-part2".device = "/dev/disk/by-id/ata-SAMSUNG_MZ7LH480HAHQ-00005_S45PNA0NB21130-part2";

    # Espresso drives (Samsung SSDs  960GB)
    "luks-espresso-ata-SAMSUNG_MZ7KM960HAHP-00005_S2HTNX0H626552" = {
      device = "/dev/disk/by-uuid/725756dc-480b-4be9-a204-a4192f609caf";
      allowDiscards = true;
    };
    "luks-espresso-ata-SAMSUNG_MZ7KM960HAHP-00005_S2HTNX0HB01819" = {
      device = "/dev/disk/by-uuid/4f18b2a3-30cd-401d-a128-e579de0ef6ec";
      allowDiscards = true;
    };

    # Molasses drives (Seagate HDDs)
    "luks-molasses-ata-ST16000NT001-3LV101_ZR6143T5" = {
      device = "/dev/disk/by-uuid/f1e9e8c3-23c9-4985-adc7-41e62a5615a9";
    };
    "luks-molasses-ata-ST16000NT001-3LV101_ZR70WRGB" = {
      device = "/dev/disk/by-uuid/40759e67-90af-4b8c-b485-3d32cd0f4ed4";
    };

  };

  fileSystems."/" =
    {
      device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/DB92-A87A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/espresso" =
    {
      device = "espresso";
      fsType = "zfs";
    };

  fileSystems."/mnt/molasses" =
    {
      device = "molasses";
      fsType = "zfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/f89741dd-0cd2-409e-b7e0-3e881f701c2c"; }
      { device = "/dev/disk/by-uuid/9d00f87e-ce9d-4549-95b5-4fc361e9d3ac"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.hostId = "dead1212";
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
